[env:stamplc]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
monitor_speed = 115200
build_unflags =
    -std=gnu++11
    -std=gnu++14
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

    ; 通信バッファ容量をマイコン向けに縮小
    -DMCPROTOCOL_SERIAL_MAX_REQUEST_FRAME_BYTES=768
    -DMCPROTOCOL_SERIAL_MAX_RESPONSE_FRAME_BYTES=768
    -DMCPROTOCOL_SERIAL_MAX_REQUEST_DATA_BYTES=384
lib_deps =
    fa-yoshinobu/mcprotocol-serial-cpp@4.2.1
    m5stack/M5StamPLC@1.2.0
    m5stack/M5Unified@0.2.13
    m5stack/M5GFX@0.2.28
